In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import pickle

In [3]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data=data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [5]:
## Encode the categorical features
label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"])

In [7]:
## One hot encode the "Geography" column
onehot_encoder_geo=OneHotEncoder(handle_unknown="ignore")
geo_encoded=onehot_encoder_geo.fit_transform(data[["Geography"]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(["Geography"]))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
##combine the one hot encoded columns with the original dataframe   
data=pd.concat([data.drop("Geography", axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [9]:
X=data.drop("EstimatedSalary", axis=1)
y=data['EstimatedSalary']

In [11]:
## Split the data into training and testing sets
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
##Scale the features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
# save the pickle files 
with open ('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)
with open ('onehot_encoder_geo.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_geo, f)
with open ('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [15]:
## ANN regression model
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [16]:
# Biuld the model
model=Sequential([
    Dense(64, activation="relu", input_shape=(X_train.shape[1],)),
    Dense(32, activation="relu"),
    Dense(1) ## Default activation for regression is linear
])

WARNING:tensorflow:From d:\GenAi Course\ANN Classification project\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [18]:
## compile the model
model.compile(optimizer="adam", loss="mean_absolute_error",metrics=["mae"])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [19]:
## logs
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

# setup tensorboard
log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [20]:
# Setup early stopping
early_stopping_callback=EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

In [21]:
# Train the model
history=model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, callbacks=[tensorboard_callback, early_stopping_callback])

Epoch 1/100
WARNING:tensorflow:From d:\GenAi Course\ANN Classification project\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\GenAi Course\ANN Classification project\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 1s 3ms/step - loss: 100369.2891 - mae: 100369.2891 - val_loss: 98486.2109 - val_mae: 98486.2109
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 99532.3438 - mae: 99532.3438 - val_loss: 96807.3750 - val_mae: 96807.3750
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 96613.3594 - mae: 96613.3594 - val_loss: 92493.8828 - val_mae: 92493.8828
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 90801.0078 - mae: 90801.0078 - val_loss: 85295.8906 - val_mae: 85295.8906
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 82424.0234 - mae: 82424.0234 - val_loss: 76276.2812 - val_mae: 76276.2812
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 72895.1562 - mae: 72895.1562 - val_loss: 67251.7812 - val_mae: 67251.7812
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 64062.2461 - mae: 64062.2461 - val_loss: 59805.3789 - val_mae: 59805.3789
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 57444.6406 - mae: 57444.6406 - val_loss: 54912.5508 - val_mae: 54912.5508
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 53499.3008 - mae: 53499.3008 - val_loss: 52428.0547 - val_mae: 52428.0547
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 51623.7188 - mae: 51623.7188 - val_loss: 51480.3555 - val_mae: 51480.3555
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 50880.9766 - mae: 50880.9766 - val_loss: 51189.8125 - val_mae: 51189.8125
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 50598.7578 - mae: 50598.7578 - val_loss: 51077.4844 - val_mae: 51077.4844
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 50452.6523 - mae: 50452.6523 - val_loss: 51001.5859 - val_mae: 51001.5859
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 50365.0078 - mae: 50365.0078 - val_loss: 50932.2656 - val_mae: 50932.2656
Epoch 15/100
250/250 [==============================] - 0s 1ms/step - loss: 50295.5000 - mae: 50295.5000 - val_loss: 50875.9414 - val_mae: 50875.9414
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 50230.9570 - mae: 50230.9570 - val_loss: 50818.9609 - val_mae: 50818.9609
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 50178.9609 - mae: 50178.9609 - val_loss: 50771.6445 - val_mae: 50771.6445
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 50130.2305 - mae: 50130.2305 - val_loss: 50731.0547 - val_mae: 50731.0547
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: 50088.3906 - mae: 50088.3906 - val_loss: 50699.1094 - val_mae: 50699.1094
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 50049.0156 - mae: 50049.0156 - val_loss: 50671.8477 - val_mae: 50671.8477
Epoch 21/100
250/250 [==============================] - 0s 2ms/step - loss: 50014.1953 - mae: 50014.1953 - val_loss: 50640.4453 - val_mae: 50640.4453
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 49981.7969 - mae: 49981.7969 - val_loss: 50610.0664 - val_mae: 50610.0664
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 49949.7422 - mae: 49949.7422 - val_loss: 50580.0430 - val_mae: 50580.0430
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 49922.6914 - mae: 49922.6914 - val_loss: 50564.6367 - val_mae: 50564.6367
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 49895.0156 - mae: 49895.0156 - val_loss: 50544.2305 - val_mae: 50544.2305
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 49873.6758 - mae: 49873.6758 - val_loss: 50516.6562 - val_mae: 50516.6562
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 49850.9609 - mae: 49850.9609 - val_loss: 50495.8984 - val_mae: 50495.8984
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 49829.1094 - mae: 49829.1094 - val_loss: 50474.7031 - val_mae: 50474.7031
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49812.2109 - mae: 49812.2109 - val_loss: 50469.1211 - val_mae: 50469.1211
Epoch 30/100
250/250 [==============================] - 0s 1ms/step - loss: 49791.9531 - mae: 49791.9531 - val_loss: 50452.1445 - val_mae: 50452.1445
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 49773.1836 - mae: 49773.1836 - val_loss: 50424.4766 - val_mae: 50424.4766
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 49755.9531 - mae: 49755.9531 - val_loss: 50417.4766 - val_mae: 50417.4766
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49737.9844 - mae: 49737.9844 - val_loss: 50399.6641 - val_mae: 50399.6641
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 49720.9609 - mae: 49720.9609 - val_loss: 50395.5195 - val_mae: 50395.5195
Epoch 35/100
250/250 [==============================] - 0s 1ms/step - loss: 49710.7539 - mae: 49710.7539 - val_loss: 50393.6328 - val_mae: 50393.6328
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 49692.8125 - mae: 49692.8125 - val_loss: 50376.0508 - val_mae: 50376.0508
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 49676.7578 - mae: 49676.7578 - val_loss: 50374.7461 - val_mae: 50374.7461
Epoch 38/100
250/250 [==============================] - 0s 1ms/step - loss: 49662.7227 - mae: 49662.7227 - val_loss: 50362.8125 - val_mae: 50362.8125
Epoch 39/100
250/250 [==============================] - 0s 1ms/step - loss: 49650.0156 - mae: 49650.0156 - val_loss: 50361.0898 - val_mae: 50361.0898
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 49636.4258 - mae: 49636.4258 - val_loss: 50342.1250 - val_mae: 50342.1250
Epoch 41/100
250/250 [==============================] - 0s 1ms/step - loss: 49623.5195 - mae: 49623.5195 - val_loss: 50344.9219 - val_mae: 50344.9219
Epoch 42/100
250/250 [==============================] - 0s 1ms/step - loss: 49610.0430 - mae: 49610.0430 - val_loss: 50342.9258 - val_mae: 50342.9258
Epoch 43/100
250/250 [==============================] - 0s 1ms/step - loss: 49601.9258 - mae: 49601.9258 - val_loss: 50351.8320 - val_mae: 50351.8320
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 49590.1797 - mae: 49590.1797 - val_loss: 50335.7539 - val_mae: 50335.7539
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49578.3281 - mae: 49578.3281 - val_loss: 50336.8516 - val_mae: 50336.8516
Epoch 46/100
250/250 [==============================] - 0s 1ms/step - loss: 49571.8008 - mae: 49571.8008 - val_loss: 50334.5664 - val_mae: 50334.5664
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 49561.2109 - mae: 49561.2109 - val_loss: 50331.3867 - val_mae: 50331.3867
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49550.5000 - mae: 49550.5000 - val_loss: 50319.4688 - val_mae: 50319.4688
Epoch 49/100
250/250 [==============================] - 0s 1ms/step - loss: 49542.0898 - mae: 49542.0898 - val_loss: 50316.5156 - val_mae: 50316.5156
Epoch 50/100
250/250 [==============================] - 0s 2ms/step - loss: 49534.2461 - mae: 49534.2461 - val_loss: 50316.3008 - val_mae: 50316.3008
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 49525.6133 - mae: 49525.6133 - val_loss: 50312.6875 - val_mae: 50312.6875
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 49518.3516 - mae: 49518.3516 - val_loss: 50314.8320 - val_mae: 50314.8320
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 49512.1992 - mae: 49512.1992 - val_loss: 50317.4492 - val_mae: 50317.4492
Epoch 54/100
250/250 [==============================] - 0s 2ms/step - loss: 49504.7773 - mae: 49504.7773 - val_loss: 50317.3086 - val_mae: 50317.3086
Epoch 55/100
250/250 [==============================] - 0s 2ms/step - loss: 49494.6914 - mae: 49494.6914 - val_loss: 50311.4727 - val_mae: 50311.4727
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 49487.0469 - mae: 49487.0469 - val_loss: 50308.5508 - val_mae: 50308.5508
Epoch 57/100
250/250 [==============================] - 0s 2ms/step - loss: 49484.8398 - mae: 49484.8398 - val_loss: 50293.5625 - val_mae: 50293.5625
Epoch 58/100
250/250 [==============================] - 0s 1ms/step - loss: 49479.4375 - mae: 49479.4375 - val_loss: 50306.1445 - val_mae: 50306.1445
Epoch 59/100
250/250 [==============================] - 0s 2ms/step - loss: 49470.5273 - mae: 49470.5273 - val_loss: 50294.6133 - val_mae: 50294.6133
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 49464.0156 - mae: 49464.0156 - val_loss: 50295.9023 - val_mae: 50295.9023
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 49459.9492 - mae: 49459.9492 - val_loss: 50298.1211 - val_mae: 50298.1211
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 49451.9219 - mae: 49451.9219 - val_loss: 50295.9531 - val_mae: 50295.9531

In [23]:
%load_ext tensorboard
%tensorboard --logdir regressionlogs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6007 (pid 30056), started 0:00:32 ago. (Use '!kill 30056' to kill it.)

In [24]:
## Evaluate the model
test_loss, test_mae=model.evaluate(X_test, y_test)
print(f"Test MAE: {test_mae}")

63/63 [==============================] - 0s 1ms/step - loss: 50293.5625 - mae: 50293.5625
Test MAE: 50293.5625

In [25]:
model.save("regression_model.h5")

d:\GenAi Course\ANN Classification project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(